name: Deploy Development

on:
  push:
    branches: [ develop ]
  # Can be activated manually
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Push to sips
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SIPS_SSH_KEY }}
      run: sh dev-deploy.sh